# Generated by Django 4.0.2 on 2022-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_document_datecreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
