# Generated by Django 4.0.2 on 2022-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_document_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name_document',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
